### ISSUE TITLE
Dataset Release Issue

### ISSUE THREAD

**Issue by Chao-Ye** [awslabs/hypergraph-tabular-lm#5]
Thank you for your exciting work; modeling tabular data using hypergraphs is fantastic. 
I am very interested in your work and would like to replicate your experiments. 
Do you have any plans to release the dataset you used? It would be very helpful to me.

**Comment by SOUMAJYOTI** [comment]
We plan to release the dataset soon. Although we do not have a tentative timeline for the release,  hopefully we can release it by the end of this year.
